language: node_js
node_js: 10.16.2

sudo: required

services:
  - docker

script:
  - docker-compose up --build -d
  - docker exec visits-node npm run test

# deploy:
#   provider: heroku
#   api_key: 'kererer'
#   on:
#     branch: master
