sudo: required
services:
  - docker

script:
  - docker-compose up --build -d
  - docker run visits-node npm run test

# deploy:
#   provider: heroku
#   api_key: 'kererer'
#   on:
#     branch: master
