sudo: required
services:
  - docker

before_install:
  - docker-compose up --build

script:
  - docker run multi-docker/react-test npm run test

# deploy:
#   provider: heroku
#   api_key: 'kererer'
#   on:
#     branch: master
